[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
default = []
blocker-seed-runtime = ["dep:zephium-blocker", "zephium-blocker/runtime"]
blocker-seed-webkit = ["dep:zephium-blocker", "zephium-blocker/webkit"]

[dependencies]
base64.workspace = true
zephium-core.workspace = true
zephium-blocker = { workspace = true, optional = true }
flate2 = { version = "=1.1.9", default-features = false, features = ["rust_backend"] }
serde.workspace = true
serde_json.workspace = true
sha2 = "=0.10.9"
ring.workspace = true
tempfile.workspace = true
toml = "0.9"

[target.'cfg(target_os = "macos")'.dependencies]
libc = "=0.2.189"
