#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
check="${root}/scripts/ci/needs-rust.sh"

expect() {
  local want="$1"
  shift
  local got
  got="$(printf '%s\n' "$@" | "${check}")"
  if [[ "${got}" != "${want}" ]]; then
    echo "needs-rust: expected ${want} for: $*" >&2
    exit 1
  fi
}

expect false docs/frontend.md README.md
expect false .coderabbit.yaml .github/ISSUE_TEMPLATE/bug_report.yml .github/REPOSITORY.md CODEOWNERS
expect false frame/bundle-budgets.json frame/src/features/settings/components/sections/AppearancePage.svelte
# Compiled into desktop by frame_sources.rs.
expect true frame/src/features/tabs/components/TabRow.svelte
# Regenerated by the desktop tests.
expect true frame/src/shared/ipc/bindings.ts
expect true docs/frontend.md crates/zephium-core/src/lib.rs
expect true pnpm-lock.yaml
expect true .github/workflows/ci.yml
