#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
check="${root}/scripts/ci/scope.sh"

# expect RUST FRONTEND WORKFLOWS PATH...
expect() {
  local want="rust=$1 frontend=$2 workflows=$3"
  shift 3
  local got
  got="$(printf '%s\n' "$@" | "${check}" | paste -sd ' ' -)"
  if [[ "${got}" != "${want}" ]]; then
    echo "scope: expected '${want}', got '${got}' for: $*" >&2
    exit 1
  fi
}

expect false false false docs/frontend.md README.md .github/REPOSITORY.md
expect false false false .coderabbit.yaml .github/ISSUE_TEMPLATE/bug_report.yml CODEOWNERS
expect false true false frame/bundle-budgets.json frame/src/features/settings/components/sections/AppearancePage.svelte
expect false true false pnpm-lock.yaml package.json
# Compiled into desktop by frame_sources.rs.
expect true true false frame/src/features/tabs/components/TabRow.svelte
# Regenerated by the desktop tests.
expect true true false frame/src/shared/ipc/bindings.ts
expect true false false docs/frontend.md crates/zephium-core/src/lib.rs
expect true false false Cargo.lock desktop/src/lib.rs
expect true true true .github/workflows/ci.yml
expect true true true scripts/ci/scope.sh
expect true true false desktop/tauri.conf.json
